{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sonny.serviceAccountName" . }}
  labels:
{{ include "sonny.labels" . | nindent 4 }}
{{- end -}}
