name: "Bump, Tag, Build, and Publish"
# SECRETS NEEDED:
# CR_USERNAME - Container Registry Username (github or dockerhub)
# CR_PAT - Container registry Personal access token with push priveledges
# CF_API_KEY - ChartMuseum API Key with permission to push
# CF_REPO_URL - ChartMusuem REPO URL in the format: 'https://h.cfcr.io/bsord/charts'
# GITHUB_TOKEN - This one is assumed, provided by github automatically

env:
  # Docker image name to publish to
  IMAGE_NAME: bsord/sonny

on:
  push:
    branches:
      - "master"

jobs:
  bump-tag-publish:
    name: "Bump, Tag, Build, and Publish"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: Get next semver
        id: get-next-version
        uses: bsord/conventional-changelog-action@v3.5.0
        with:
          github-token: ${{ secrets.github_token }}
          tag-prefix: ''
          skip-version-file: true
          dry-run: true

      - name: Update source code versions
        run: |
          sed -r -i 's/(\"version\":[^*]\")([[:alnum:].]*)/\1${{ steps.get-next-version.outputs.version }}/g' package.json
          sed -r -i 's/(version:[^*]|appVersion:[^*])([[:alnum:].]*)/\1${{ steps.get-next-version.outputs.version }}/g' ./chart/Chart.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: "chore(version): Bump to: ${{ steps.get-next-version.outputs.version }}"
          tag: "${{ steps.get-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout source code
        uses: "actions/checkout@v2"

      - name: Conventional Changelog Action
        uses: bsord/conventional-changelog-action@v3.5.0
        with:
          github-token: ${{ secrets.github_token }}
          tag-prefix: ''
          skip-version-file: true

      - name: Build and publish docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bsord/sonny
          username: ${{ secrets.secrets.CR_USERNAME }}
          password: ${{ secrets.secrets.CR_PAT }}
          tags: "latest,${{ steps.get-next-version.outputs.version }}"

      - name: Push Helm Chart
        uses: bsord/helm-push@v2
        with:
          access-token: ${{ secrets.CF_API_KEY }}
          repository-url: ${{ secrets.CF_REPO_URL }} 
          force: true
          chart-folder: chart
      


