  
# This is a basic workflow to help you get started with Actions

name: 'Push Helm Chart Manual'

on: 
  workflow_dispatch:
jobs:
  push-helm-chart:
    runs-on: ubuntu-latest
    name: Push helm chart to CodeFresh repo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push Helm Chart
        uses: bsord/helm-push@v1
        with:
          access-token: ${{ secrets.CF_API_KEY }}
          repository-url: 'https://h.cfcr.io/bsord/charts'
          force: true
          chart-folder: chart