  
# This is a basic workflow to help you get started with Actions

name: 'Push Helm Chart'

on:
  push:
    tags:
    - '*'
jobs:
  push-helm-chart:
    runs-on: ubuntu-latest
    name: Push helm chart to CodeFresh repo
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        id: checkout
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          echo $VERSION
          [ "$VERSION" == "master" ] && VERSION=latest
          echo ::set-output name=tag::$VERSION}
      - name: Push Helm Chart
        uses: bsord/helm-push@v2
        with:
          access-token: ${{ secrets.CF_API_KEY }}
          repository-url: 'https://h.cfcr.io/bsord/charts'
          force: true
          chart-folder: chart
          version: ${{ steps.checkout.outputs.tag }}
          appVersion: ${{ steps.checkout.outputs.tag }}